import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";

// Petite fonction pour récupérer seulement le HTML
function extractHtmlFromMarkdown(content: string): string {
  if (!content) return "";

  // Cherche un bloc ```html ... ```
  const htmlBlock =
    content.match(/```html([\s\S]*?)```/i) || content.match(/```([\s\S]*?)```/i);

  if (htmlBlock && htmlBlock[1]) {
    return htmlBlock[1].trim();
  }

  // Sinon on renvoie tout le contenu tel quel
  return content.trim();
}

export async function POST(req: NextRequest) {
  try {
    const { prompt } = await req.json();

    if (!prompt || typeof prompt !== "string") {
      return NextResponse.json(
        { error: "Missing prompt" },
        { status: 400 }
      );
    }

    const apiKey = process.env.V0_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "Missing V0_API_KEY in environment" },
        { status: 500 }
      );
    }

    // 1) Appel à l’API v0
    const v0Response = await fetch("https://api.v0.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "v0-1.5-md",
        messages: [
          {
            role: "system",
            content:
              "Tu es un générateur de site vitrine. Retourne UNIQUEMENT du code HTML complet (avec <!DOCTYPE html>, <html>, <head>, <body>), sans texte explicatif en dehors des balises HTML.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
        // Pas besoin de stream pour l’instant
        stream: false,
      }),
    });

    if (!v0Response.ok) {
      const errorText = await v0Response.text();
      console.error("v0 API error:", errorText);
      return NextResponse.json(
        { error: "v0 API error", details: errorText },
        { status: 500 }
      );
    }

    const data = await v0Response.json();

    const rawContent =
      data?.choices?.[0]?.message?.content ??
      data?.choices?.[0]?.delta?.content ??
      "";

    const html = extractHtmlFromMarkdown(rawContent);

    if (!html) {
      return NextResponse.json(
        { error: "No HTML content generated by v0" },
        { status: 500 }
      );
    }

    // 2) On génère un petit ID pour l’URL (comme tu faisais avec [id])
    const id = crypto.randomUUID();

    // 3) Ici, on ne sauvegarde rien (Airtable le fera via n8n),
    // on renvoie juste ce qu’il faut pour que n8n puisse mettre à jour la colonne "Lien site démo (URL)"
    const baseUrl =
      process.env.NEXT_PUBLIC_BASE_URL ||
      "https://lynxio-v0-generator.vercel.app";

    const siteUrl = `${baseUrl}/site/${id}`;

    // OPTION : si tu veux plus tard servir ce HTML via /site/[id],
    // tu stockeras (id, html) dans Airtable, Supabase ou autre.

    return NextResponse.json(
      {
        id,
        html,
        siteUrl,
      },
      { status: 200 }
    );
  } catch (err: any) {
    console.error("generate-site route error:", err);
    return NextResponse.json(
      { error: "Server error", details: err?.message ?? String(err) },
      { status: 500 }
    );
  }
}
